---
- name: Deshabilitar login de root por SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    backup: yes
  notify: Reiniciar ssh

- name: Limitar intentos de autenticacion a 3
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?MaxAuthTries'
    line: 'MaxAuthTries 3'

- name: Deshabilitar X11Forwarding
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?X11Forwarding'
    line: 'X11Forwarding no'

- name: Activar LogLevel VERBOSE para SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?LogLevel'
    line: 'LogLevel VERBOSE'

- name: Reducir tiempo de gracia de login a 30 segundos
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?LoginGraceTime'
    line: 'LoginGraceTime 30'

- name: Deshabilitar contrasenas vacias
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitEmptyPasswords'
    line: 'PermitEmptyPasswords no'

- name: Habilitar compresion solo despues de autenticacion
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Compression'
    line: 'Compression delayed'
